biketrax_cloud/config/routes.rb
Rails.application.routes.draw do
  resources :bike_paths do
    collection do
      get 'add_point'
      post 'add_points'
    end
  end

end

biketrax_cloud/app/models/bike_path.rb
class BikePath < ActiveRecord::Base
  has_many :points

  def polyline_points
    self.points.map(&:latlng)
  end

  def polyline
    Polylines::Encoder.encode_points(self.polyline_points)
  end
end

biketrax_cloud/app/models/point.rb
class Point < ActiveRecord::Base
  belongs_to :bike_path

  def latlng
    [self.latitude, self.longitude]
  end
end

biketrax_cloud/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

biketrax_cloud/app/controllers/bike_paths_controller.rb
require 'csv'

class BikePathsController < ApplicationController
  before_action :set_bike_path, only: [:show, :edit, :update, :destroy]

  skip_before_filter :verify_authenticity_token, only: [:add_points]

  # GET /bike_paths
  # GET /bike_paths.json
  def index
    @bike_paths = BikePath.all
  end

  # GET /bike_paths/1
  # GET /bike_paths/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json {
        render :json => @bike_path.to_json(:methods => [:polyline], :only => [:name])
      }
    end
  end

  def add_point
    point = Point.new
    point.longitude = params[:longitude]
    point.latitude = params[:latitude]
    point.bike_path = BikePath.first
    point.save

    render json: 'OK'
  end

  def add_points
    csv_text = request.body.read
    csv = CSV.parse(csv_text, :headers => true)
    csv.each do |row|
      puts row
    end

    render json: 'OK'
  end

  # GET /bike_paths/new
  def new
    @bike_path = BikePath.new
  end

  # GET /bike_paths/1/edit
  def edit
  end

  # POST /bike_paths
  # POST /bike_paths.json
  def create
    @bike_path = BikePath.new(bike_path_params)

    respond_to do |format|
      if @bike_path.save
        format.html { redirect_to @bike_path, notice: 'Bike path was successfully created.' }
        format.json { render :show, status: :created, location: @bike_path }
      else
        format.html { render :new }
        format.json { render json: @bike_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bike_paths/1
  # PATCH/PUT /bike_paths/1.json
  def update
    respond_to do |format|
      if @bike_path.update(bike_path_params)
        format.html { redirect_to @bike_path, notice: 'Bike path was successfully updated.' }
        format.json { render :show, status: :ok, location: @bike_path }
      else
        format.html { render :edit }
        format.json { render json: @bike_path.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bike_paths/1
  # DELETE /bike_paths/1.json
  def destroy
    @bike_path.destroy
    respond_to do |format|
      format.html { redirect_to bike_paths_url, notice: 'Bike path was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_bike_path
    @bike_path = BikePath.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def bike_path_params
    params.require(:bike_path).permit(:name, :datetime)
  end
end

biketrax_cloud/app/helpers/application_helper.rb
module ApplicationHelper
  def google_maps_api_key
    "AIzaSyDUrYLEzdENlerV86DWWUewWx7Pf0qfpNI"
  end

  def google_api_url
    "https://maps.googleapis.com/maps/api/js"
  end

  def google_api_access
    "#{google_api_url}?key=#{google_maps_api_key}&libraries=geometry"
  end

  def google_maps_api
    content_tag(:script, :type => "text/javascript", :src => google_api_access) do
    end
  end

  def track_id_to_js(id)
    content_tag(:script, :type => "text/javascript") do
      "var js_track_id = "+id.to_s;
    end
  end
end

biketrax_cloud/app/helpers/bike_paths_helper.rb
module BikePathsHelper
end

biketrax_cloud/app/views/bike_paths/_form.html.erb
<%= form_for(@bike_path) do |f| %>
  <% if @bike_path.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike_path.errors.count, "error") %> prohibited this bike_path from being saved:</h2>

      <ul>
      <% @bike_path.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br>
    <%= f.datetime_select :datetime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

biketrax_cloud/app/views/bike_paths/edit.html.erb
<h1>Editing Bike Path</h1>

<%= render 'form' %>

<%= link_to 'Show', @bike_path %> |
<%= link_to 'Back', bike_paths_path %>

biketrax_cloud/app/views/bike_paths/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bike Paths</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Datetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bike_paths.each do |bike_path| %>
      <tr>
        <td><%= bike_path.name %></td>
        <td><%= bike_path.datetime %></td>
        <td><%= link_to 'Show', bike_path %></td>
        <td><%= link_to 'Edit', edit_bike_path_path(bike_path) %></td>
        <td><%= link_to 'Destroy', bike_path, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bike path', new_bike_path_path %>

biketrax_cloud/app/views/bike_paths/new.html.erb
<h1>New Bike Path</h1>

<%= render 'form' %>

<%= link_to 'Back', bike_paths_path %>

biketrax_cloud/app/views/bike_paths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @bike_path.name %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @bike_path.datetime %>
</p>

<%= link_to 'Edit', edit_bike_path_path(@bike_path) %> |
<%= link_to 'Back', bike_paths_path %>

<div id="map_canvas" style="height: 600px;"></div>

biketrax_cloud/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Biketrax</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= google_maps_api %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= track_id_to_js(@bike_path.id) if @bike_path %>
</head>
<body>

<%= yield %>

</body>
</html>